# Generated by Django 2.2.5 on 2019-09-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holero',
            name='languages',
        ),
        migrations.AddField(
            model_name='holero',
            name='primary_languages',
            field=models.ManyToManyField(related_name='holero_primary_languages', to='api.Language'),
        ),
        migrations.AddField(
            model_name='holero',
            name='target_languages',
            field=models.ManyToManyField(related_name='holero_target_languages', to='api.Language'),
        ),
    ]
