# Generated by Django 2.2.5 on 2019-09-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190910_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='holero',
            name='active_target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Language'),
        ),
    ]
